version: 2.1

orbs:
  python: circleci/python@1.2.0 # Updated version
  codecov: codecov/codecov@1.1.5 # Updated version

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.10" # Ensure this matches the latest compatible version
    docker:
      - image: "gbarbalinardo/kaldo:latest" # Updated to use the latest image
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Test
          command: python -m pytest -v --cov=kaldo --cov-report=xml --color=yes kaldo/tests/
      - codecov/upload:
          file: ./coverage.xml

  docs-build:
    docker:
      - image: "jgoldfar/miniconda3-latex:latest" # Consider updating the tag to the latest or a more specific version
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            conda install pip
            conda install -c conda-forge pandoc
            conda install make
            conda install -c conda-forge tensorflow=2.3
            conda install psutil>=5.7.2
      - run:
          name: Install docs dependencies
          command: pip install -r docs/doc_requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - run:
          name: Create .nojekyll
          command: cd docs/_build/html && touch .nojekyll
      - persist_to_workspace:
          root: docs/_build
          paths:
            - html

  docs-deploy:
    docker:
      - image: cibuilds/github:0.13 # An updated image that simplifies GitHub operations
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            apk add --no-cache git openssh-client # Ensure git and SSH are installed
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
            npx gh-pages -d docs/_build/html --dotfiles --message "[skip ci] Updates"

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
      - docs-build:
          requires:
            - build-and-test
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: main
