version: 2.1

orbs:
  python: circleci/python@1.2.0 # Updated version
  codecov: codecov/codecov@1.1.5 # Updated version

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.10" # Ensure this matches the latest compatible version
    docker:
      - image: "gbarbalinardo/kaldo:latest" # Updated to use the latest image
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Test
          command: python -m pytest -v --cov=kaldo --cov-report=xml --color=yes kaldo/tests/
      - codecov/upload:
          file: ./coverage.xml
workflows:
  version: 2
  main:
    jobs:
      - build-and-test